name: 'Configure SSH'
description: 'Sets up ssh with in the action context'

inputs:
  private_ssh_key:
    description: 'Github secret storing the ssh private key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Configure ssh'
      shell: bash
      run: |
        eval `ssh-agent -s`
        ssh-add - <<< '${{ inputs.private_ssh_key }}'
