swagger: "2.0"
info:
  title:
    $ref: './<environment>/config.yaml#/info/title'
  description:
    $ref: './<environment>/config.yaml#/info/description'
  version:
    $ref: './<environment>/config.yaml#/versions/api-version'
schemes:
  - https
produces:
  - application/json

host:
  $ref: './<environment>/config.yaml#/environment/host'
x-google-endpoints:
  $ref: './<environment>/config.yaml#/environment/x-google-endpoints'
x-google-backend:
  $ref: './<environment>/config.yaml#/environment/x-google-backend'

securityDefinitions:
  # This section configures basic authentication with an API key.
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"
security:
  - api_key: [ ]

paths:
  $ref: './common/endpoints.yaml#/paths'
