name: 'Setup GCloud'
description: 'Setups runner environment for a project to use GCLoud-SDK for deployment purposes'

inputs:
  config:
    description: A github secret containing the json api key from google for the desired service account that will be issuing the commands from the `gcloud` cli.
    required: true
  secrets:
    description: None
    required: true

#outputs:
#  args:
#    description: None
#    value: ${{ toJson(steps.gcp_secrets.outputs) }}

runs:
  using: 'composite'
  steps:
    - name: 'Print Input'
      shell: bash
      run: |
        echo '${{ inputs.secrets }}' > temp.txt
        keys=$(sed -E 's/.*"([A-Z_]+).*":.*|.*/\1/' temp.txt | grep -v '^[[:space:]]*$')
        echo $keys | tr ' ' '\n' | awk '{print "--build-arg " $1 "=" }'

        for i in $keys
        do
          echo "Key: $i"
          echo "${{ fromJson(inputs.secrets)[$i] }}"
        done

#        echo $keys | tr ' ' '\n' | awk '{print "--build-arg " $1 "=" }'
#        ${{ fromJson(inputs.secrets).T }}

#        echo ${{ fromJson(inputs.secrets)['T'] }}

#
#        sed 's/[\*]*//' temp.txt > temp_cleaned.txt
#        cat temp_cleaned.txt
#
#        sed 's/,$//' temp_cleaned.txt > temp_cleaned_2.txt
#        cat temp_cleaned_2.txt

#        arg_list=$(awk -F: '{print "--build-args "$1"="$2}' temp.txt)
#        echo $arg_list

#        echo "${{ inputs.config }}" >> temp.txt
#        arg_list=$(awk -F: '{print "--build-args "$1"="$2}' temp.txt)
#        cleaned_args=${arg_list//= /=}
#        echo $cleaned_args