name: 'Setup GCloud'
description: 'Setups runner environment for a project to use GCLoud-SDK for deployment purposes'

inputs:
  config:
    description: A github secret containing the json api key from google for the desired service account that will be issuing the commands from the `gcloud` cli.
    required: true
  secrets:
    description: None
    required: true

outputs:
  args:
    description: None
    value: ${{ toJson(steps.gcp_secrets.outputs) }}

runs:
  using: 'composite'
  steps:
    - name: 'Print Input'
      shell: bash
      run: |
        echo "${{ inputs.secrets }} >> temp"
        cat temp
        echo "${{ fromJson(inputs.secrets) }}" | jq "."
#        echo "${{ inputs.secrets }}" | jq "."

#        echo "${{ inputs.config }}" >> temp.txt
#        arg_list=$(awk -F: '{print "--build-args "$1"="$2}' temp.txt)
#        cleaned_args=${arg_list//= /=}
#        echo $cleaned_args
