name: Decrypt KMS Secret
description: Using the gcloud command this action decrypts all the kms secrets requested
inputs:
  key_ring:
    description: The KMS keyring that that the secrets are being taken from
    required: true
  keys:
    description: 'The keys being requested in the format (key: cipher_text)'
    required: true
  input_dir:
    description: 'The location to store the encrypted data'
    required: false
    default: '.'
  output_dir:
    description: 'The location to store the decrypted data'
    required: false
    default: '.'


runs:
  using: 'composite'
  steps:
    - name: Process KMS Input
      shell: bash
      run: |
        keys="${{ inputs.keys }}"
        echo "$keys" | grep ":" | sed 's/.enc$//' | tr -d '[ ]' > input.txt

        mkdir ./keys
        arg_list=$(awk -F: '{
           print "--ciphertext-file " input_dir"/"$2".enc --plaintext-file " output_dir"/"$1 " --key "$1 \
        }' input_dir=${{ inputs.input_dir }} output_dir=${{ inputs.output_dir }} input.txt)
        echo "$arg_list" > /tmp/kms_decrypt_input

    - name: Decrypt Keys
      shell: bash
      run: |
        cat /tmp/kms_decrypt_input | xargs -I % bash -c 'gcloud kms decrypt % --location=us-central1 --keyring=${{ inputs.key_ring }}'