name: Decrypt KMS Secret
description: Using the gcloud command this action decrypts all the kms secrets requested
inputs:
  key_ring:
    description: The KMS keyring that that the secrets are being taken from
    required: true
  keys:
    description: 'The keys being requested in the format (key: cipher_text_location)'
    required: true
  output_dir:
    description: 'The location to store the decrypted keys'
    required: false
    default: '.'

#--ciphertext-file=./config/cfr_runner.key.enc",
#"--plaintext-file=./config/cfr_runner.key",
#"--location=us-central1",
#"--keyring=cfr",
#"--key=cfr_runner_key
#


runs:
  using: 'composite'
  steps:
    - name: Process KMS Input
      shell: bash
      run: |
        keys="${{ inputs.keys }}"
        echo "$keys" | grep ":" > input.txt
        arg_list=$(awk -F: '{print "--ciphertext-file "$2 " --plaintext-file ./keys/"$1".key" " --key "$1}' input.txt)
        echo "$arg_list" > /tmp/kms_decrypt_input

    - name: Decrypt Keys
      shell: bash
      run: |
        cat /tmp/kms_decrypt_input | xargs -I % gcloud kms decrypt % --location=us-central1 --keyring=${{ inputs.key_ring }}
