name: Decrypt KMS Secret
description: Using the gcloud command this action decrypts all the kms secrets requested
inputs:
  key_ring:
    description: 'The GCP KMS keyring that the keys are retrieved from'
    required: true
  decrypt_info:
    description: 'A list of decryption requests in the format (ciphertext : key : plaintext)'
    required: true
  input_dir:
    description: 'The location where the encrypted data is stored'
    required: false
    default: '.'
  output_dir:
    description: 'The location to store the decrypted data'
    required: false
    default: '.'


runs:
  using: 'composite'
  steps:
    - name: Process KMS Input
      shell: bash
      run: |
        keys="${{ inputs.decrypt_info }}"
        echo "$keys" | grep ":" | tr -d '[ ]' > input.txt

        mkdir ${{ inputs.output_dir }}
        arg_list=$(awk -F: '{
            print "--ciphertext-file " input_dir"/"$1" --plaintext-file " output_dir"/"$3 " --key "$2;
        }' input_dir=${{ inputs.input_dir }} output_dir=${{ inputs.output_dir }} input.txt)
        echo "$arg_list" > /tmp/kms_decrypt_input

    - name: Decrypt Keys
      shell: bash
      run: |
        cat /tmp/kms_decrypt_input | xargs -I % bash -c 'gcloud kms decrypt % --location=us-central1 --keyring=${{ inputs.key_ring }}'