name: 'Setup GCloud'
description: 'Setups runner environment for a project to use GCLoud-SDK for deployment purposes'

inputs:
  gcp_credentials:
    description: 'The json api key from google for the desired service account that will be issuing the commands from the `gcloud` cli.'
    required: true
  gcp_secrets:
    description: 'Secrets from GCP that you want available for other steps and actions within a job.'
    required: false
    default: ''

outputs:
  has_secrets:
    description: boolean flag showing if the step produced any secrets
    value: ${{ steps.validation.has_secrets }}
  secrets:
    description: JSON dictionary of dynamic outputed secret values
    value: ${{ toJson(steps.gcp_secrets.outputs) }}

runs:
  using: 'composite'
  steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v2

    - name: 'Authenticate to Google Cloud'
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ inputs.gcp_credentials }}

    - name: 'Set up Cloud SDK'
      uses: google-github-actions/setup-gcloud@v0
      with:
        install_components: beta

    - name: 'Get Secrets'
      if: ${{ inputs.gcp_secrets }}
      id: gcp_secrets
      uses: google-github-actions/get-secretmanager-secrets@v0
      with:
        secrets: ${{ inputs.gcp_secrets }}

    - name: 'Has Secrets'
      id: validation
      shell: bash
      run: |
        if [ -n "${{ inputs.gcp_secrets }}" ];
        then
          echo "::set-output name has_secrets=true::"
        else
          echo "::set-output name has_secrets=false::"
        fi
