name: 'Build and Publish Image'
description: 'Builds and publishes a docker image'

inputs:
  tag:
    description: Image tag
    required: true
  dockerfile:
    description: Location of the dockerfile
    required: true
  build_context:
    description: Location for docker's build context
    required: false
    default: '.'
  build_args:
    description: Additional agruments to pass to docker build
    required: false
    default: ''
  push_args:
    description: Additional arguments to pass to docker push
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
#    - name: 'Build Image'
#      shell: bash
#      run: |
#        docker build \
#        --tag ${{ inputs.tag }} \
#        ${{ inputs.build_args }} \
#        --file ${{ inputs.dockerfile }} \
#        ${{ inputs.build_context }}

    - name: 'Configure gcp docker registry'
#      if: "${{ contains(inputs.tag, 'gcr.io') }}"
      shell: bash
      run: |
        echo "${{ inputs.tag }}"
        echo "${{ contains(inputs.tag, 'gcr.io') }}"
        gcloud auth configure-docker

#    - name: 'Publish Image'
#      shell: bash
#      run: docker push ${{ inputs.tag }}