name: 'GCP Endpoints Configuration/Update/Deployment'
description: 'Recompiles and the needed components for GCP endpoints and redelopys them'

inputs:
  gcp_project:
    description: 'The GCP project name'
    required: true
  api_subdomain:
    description: 'The subdomain of the api being deployed'
    required: true
  api_name:
    description: 'Name of the api'
    required: true
  endpoints_service_name:
    description: 'Name of the GCP endpoints service name'
    required: true
  default_service_account:
    description: 'The service account you want to run the gcloud deployment commands'
    required: true
  openapi_yaml:
    description: 'The location of the openapi yaml that defines the api endpoints'
    required: false
    default: "./openapi.yaml"

runs:
  using: 'docker'
  image: "Dockerfile"
  env: 
    GCP_PROJECT: ${{ inputs.gcp_project }}
    API_SUBDOMAIN: ${{ inputs.api_subdomain }}
    API_NAME: ${{ inputs.api_name }}
    ENDPOINTS_SERVICE_NAME: ${{ inputs.endpoints_service_name }}
    OPENAPI_YAML: ${{ inputs.openapi_yaml }}
    DEFAULT_GCP_SERVICE_ACCOUNT: ${{ inputs.default_service_account }}
