name: 'GCP Endpoints Configuration/Update/Deployment'
description: 'Recompiles and the needed components for GCP endpoints and redelopys them'
inputs:
  gcp_project:
    description: The GCP project name
    required: true
  api_subdomain:
    description: The subdomain of the api being deployed
    required: true
  default_service_account:
    description: The service account you want to run the gcloud deployment commands
    required: true
  openapi_yaml:
    description: The location of the openapi yaml that defines the api's endpoints
    required: false
    default: "./openapi.yaml"  
runs:
  using: 'docker'
  image: "Dockerfile"
  env: 
    GCP_PROJECT: ${{ inputs.gcp_project }}
    API_SUBDOMAIN: ${{ inputs.api_subdomain }}
    OPENAPI_YAML: ${{ inputs.openapi_yaml }}
    DEFAULT_GCP_SERVICE_ACCOUNT: ${{ inputs.default_service_account }}
