name: 'GCP Endpoints Configuration/Update/Deployment'
description: 'Recompiles and the needed components for GCP endpoints and redelopys them'
inputs:
  gcp_project:
    description: None
    required: true
  api_subdomain:
    description: None
    required: true
  openapi_yaml:
    description: The location of the openapi yaml that defines the endpoint
    default: "./openapi.yaml"  
runs:
  using: 'composite'
  steps:
    - run: deployment_script.sh ${{ inputs.gcp_project }} ${{ inputs.api_subdomain }} ${{ inputs.openapi_yaml }}
      shell: bash
