name: '[Template] GCP Function Deployment'

on:
  workflow_call:
    inputs:
      gcp_project:
        description: 'The GCP project name'
        type: string
        required: true
      service_account:
        description: 'The GCP service account to run the function under'
        type: string
        required: true
      function_name:
        description: 'The name of the GCP function'
        type: string
        required: true
      entry_point:
        description: 'The function entry point'
        type: string
        required: true
      runtime:
        description: 'The GCP function runtime'
        type: string
        required: false
        default: 'python37'
      gcp_secrets:
        description: 'Secrets from GCP that you want available in the docker container'
        type: string
        required: false
        default: ''
      environment_variables:
        description: 'List of environment variables to pass to set in the function'
        type: string
        required: false
        default: ''
      function_dir:
        description: 'Location of the directory containing the GCP function code'
        type: string
        required: false
        default: '.'
      extra_function_args:
        description: 'Extra args to pass to the GCP function deploy command'
        type: string
        required: false
        default: ''
    secrets:
      gcp_credentials:
        description: 'A github secret containing the json api key from google for the desired service account that will be issuing the commands from the `gcloud` cli.'
        required: true

jobs:
  function_deployment:
    name: 'GCP Function Deployment'
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup GCloud SDK'
        id: gcp
        uses: Auddia/cicd/actions/setup_gcloud@main
        with:
          gcp_credentials: ${{ secrets.gcp_credentials }}
          gcp_secrets: ${{ inputs.gcp_secrets }}

      - name: 'Parse ENV variables'
        id: deploy_config
        shell: bash
        run: |
          environment_variables="${{ inputs.environment_variables }}"
          if [ -n "$environment_variables" ];
          then
            value=$(echo "$environment_variables" | tr ':' '=' | tr -d [:space:])
          else
            value="DUMMY=0"
          fi

          secret_args="${{ steps.gcp.outputs.secrets }}"
          echo "$secret_args" | grep ":" | tr -d "[\":]"

          echo "env_vars=${value}" >> "$GITHUB_ENV"

      - name: 'GCP Function Deployment'
        shell: bash
        run: |
          cd ${{ inputs.function_dir }}

          gcloud beta functions deploy ${{ inputs.function_name }} \
            ${{ inputs.extra_function_args }} \
            --runtime ${{ inputs.runtime }} \
            --service-account ${{ inputs.service_account }} \
            --entry-point ${{ inputs.entry_point }} \
            --update-env-vars '${{ env.env_vars }}'
