name: '[Template] Openapi Update'

on:
  workflow_call:
    inputs:
      gcp_project:
        description: 'The GCP project name'
        type: string
        required: true
      api_subdomain:
        description: 'The subdomain of the api being deployed'
        type: string
        required: true
      api_name:
        description: 'Name of the api'
        type: string
        required: true
      endpoints_service_name:
        description: 'Name of the GCP endpoints service name'
        type: string
        required: true
      default_service_account:
        description: 'The service account you want to run the gcloud deployment commands'
        type: string
        required: true

      openapi_dir:
        description: 'The directory location of all the openapi templates and configurations'
        type: string
        required: false
        default: "./"
      template:
        description: 'The name of the template yaml file'
        type: string
        required: false
        default: 'template.yaml'
      openapi_yaml:
        description: 'The location of the openapi yaml that defines the endpoint'
        type: string
        required: false
        default: "./openapi.yaml" 

      environment_key:
        description: 'Key in the template to replace with the environment value.'
        type: string
        required: false
        default: '<environment>'
      environment_value:
        description: 'Value that will replace the environment key in the template.'
        type: string
        required: false
        default: 'production'
      
    secrets:
      gcp_credentials:
        required: true 

jobs:
  openapi_update:
    name: 'OpenAPI Update Deployment Job'
    runs-on: ubuntu-latest
    steps:
      - name: 'GCloud SDK Setup'
        uses: Auddia/cicd/actions/setup_gcloud@v03
        with:
          gcp_credentials: ${{ secrets.gcp_credentials }}

      - name: 'Compile OpenAPI YAML File'
        uses: Auddia/cicd/actions/compile_openapi@v03
        with:
          openapi_dir: ${{ inputs.openapi_dir }}
          template: ${{ inputs.template }}
          outfile: ${{ inputs.openapi_yaml }}
          environment_key: ${{ inputs.environment_key }}
          environment_value: ${{ inputs.environment_value }}

      - name: 'GCP Deployment'
        uses: Auddia/cicd/actions/configure_gcp_endpoints@v03
        with:
          gcp_project: ${{ inputs.gcp_project }}
          api_subdomain: ${{ inputs.api_subdomain }}
          api_name: ${{ inputs.api_name }}
          endpoints_service_name: ${{ inputs.endpoints_service_name }}
          default_service_account: ${{ inputs.default_service_account }}
          openapi_yaml: ${{ inputs.openapi_yaml }}
