name: '[Action Test] compile_openapi'

on:
  workflow_dispatch:

jobs:
  env_one:
    name: 'Environment One'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: 'Compile OpenAPI File'
        uses: ./actions/compile_openapi
        with:
          openapi_dir: ./resources/test_openapi_template
          environment_value: env_one

      - name: 'Validate OpenAPI Created'
        shell: bash
        run: |
          ls -la
          source ./scripts/test_functions.sh
          title_line=$(grep "title" ./openapi.yaml)
          expected="title: ENV ONE"

          echo "Output: ${title_line}"
          echo "Expected: ${expected}"
          strings_equal "$title_line" "$expected"

  env_two:
    name: 'Environment Two'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: 'Compile OpenAPI File'
        uses: ./actions/compile_openapi
        with:
          openapi_dir: ./resources/test_openapi_template
          environment_value: env_two

      - name: 'Validate OpenAPI Created'
        shell: bash
        run: |
          ls -la
          source ./scripts/test_functions.sh
          title_line=$(grep "title" ./openapi.yaml)
          expected="title: ENV TWO"

          echo "Output: ${title_line}"
          echo "Expected: ${expected}"
          strings_equal "$title_line" "$expected"
