name: '[Workflow Test] python_test'


on:
  workflow_dispatch:

jobs:
  test_setup:
    name: 'Setup Test'
    uses: ./.github/workflows/python_test.yml
    with:
      python_versions: "[\"3.7\", \"3.8\"]"
      test_dir: ./resources/sample_python_tests
      setup_dir: ./resources/sample_python_tests

  test_requirements:
    name: 'Requirements Test'
    uses: ./.github/workflows/python_test.yml
    with:
      python_versions: "[\"3.7\", \"3.8\"]"
      test_dir: ./resources/sample_python_tests
      test_setup: false
      requirements: ./resources/sample_python_tests/requirements.txt
