name: '[Action Test] build_and_publish_image'

on:
  workflow_dispatch:
    inputs:
      gcp_secret:
        description: 'GCP Secret'
        required: true

jobs:
  generic_image:
    name: 'Generic Image'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: 'Build and Publish Image'
        uses: ./actions/build_and_publish_image
        with:
          tag: auddia_test_image:${{ github.sha }}
          dockerfile: ./resources/test_docker_env/Dockerfile
          build_context: ./resources/test_docker_env
          build_config: |
            TEST_ONE: ONE
            TEST_TWO: TWO

      - name: 'Validate Image'
        shell: bash
        run: |
          source ./scripts/test_functions.sh
          image_output=$(docker run auddia_test_image:${{ github.sha }})

          expected="TEST_ONE: ONE
            TEST_TWO: TWO
            TEST_THREE: "

          echo "Output: ${output}"
          echo "Expected: ${expected}"
          strings_equal "$image_output" "$expected"

  gcp_image:
    name: 'GCP Image'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: 'GCloud SDK Setup'
        uses: ./actions/setup_gcloud
        with:
          gcp_credentials: ${{ github.event.inputs.gcp_secret }}

      - name: 'Build and Publish Image'
        uses: ./actions/build_and_publish_image
        with:
          tag: gcr.io/vodacast-staging/auddia_test_image:${{ github.sha }}
          dockerfile: ./resources/test_docker_env/Dockerfile
          build_context: ./resources/test_docker_env
          build_config: |
            TEST_ONE: ONE
            TEST_TWO: TWO

      - name: 'Validate Image'
        shell: bash
        run: |
          source ./scripts/test_functions.sh
          image_output=$(docker run gcr.io/vodacast-staging/auddia_test_image:${{ github.sha }})

          expected="TEST_ONE: ONE
            TEST_TWO: TWO
            TEST_THREE: "

          echo "Output: ${output}"
          echo "Expected: ${expected}"
          strings_equal "$image_output" "$expected"

  generic_image_with_secrets:
    name: 'Generic Image w/ Secrets'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: 'GCloud SDK Setup'
        id: gcp
        uses: ./actions/setup_gcloud
        with:
          gcp_credentials: ${{ github.event.inputs.gcp_secret }}
          gcp_secrets: |
            TEST_ONE: projects/vodacast-staging/secrets/vodacast-postgres-password

      - name: 'Build and Publish Image'
        uses: ./actions/build_and_publish_image
        with:
          tag: auddia_test_image:${{ github.sha }}
          dockerfile: ./resources/test_docker_env/Dockerfile
          build_context: ./resources/test_docker_env
          gcp_secrets: ${{ steps.gcp.outputs.secrets }}
          build_config: |
            TEST_TWO: TWO
            TEST_THREE: PI

      - name: 'Validate Image'
        shell: bash
        run: |
          source ./scripts/test_functions.sh
          image_output=$(docker run auddia_test_image:${{ github.sha }})

          expected="TEST_ONE: ***
            TEST_TWO: TWO
            TEST_THREE: PI"

          echo "Output: ${output}"
          echo "Expected: ${expected}"
          strings_equal "$image_output" "$expected"

  gcp_image_with_secrets:
    name: 'GCP Image w/ Secrets'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: 'GCloud SDK Setup'
        id: gcp
        uses: ./actions/setup_gcloud
        with:
          gcp_credentials: ${{ github.event.inputs.gcp_secret }}
          gcp_secrets: |
            TEST_ONE: projects/vodacast-staging/secrets/vodacast-postgres-password
            TEST_THREE: projects/vodacast-staging/secrets/vodacast-postgres-password

      - name: 'Build and Publish Image'
        uses: ./actions/build_and_publish_image
        with:
          tag: gcr.io/vodacast-staging/auddia_test_image:${{ github.sha }}
          dockerfile: ./resources/test_docker_env/Dockerfile
          build_context: ./resources/test_docker_env
          gcp_secrets: '${{ steps.gcp.outputs.secrets }}'
          build_config: |
            TEST_TWO: TWO
            TEST_FOUR: PI

      - name: 'Validate Image'
        shell: bash
        run: |
          source ./scripts/test_functions.sh
          image_output=$(docker run gcr.io/vodacast-staging/auddia_test_image:${{ github.sha }})

          expected="TEST_ONE: ***
            TEST_TWO: TWO
            TEST_THREE: ***
            TEST_FOUR: PI"

          echo "Output: ${output}"
          echo "Expected: ${expected}"
          strings_equal "$image_output" "$expected"
