on:
  workflow_dispatch:
    gcp_secret:
      description: 'GCP Secret'
      required: true


jobs:
  test_job:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: GCloud SDK Setup
        uses: ./actions/setup_gcloud
        with:
          gcp_credentials: ${{ github.event.inputs.gcp_secret }}

      - name: decrypt_kms
        uses: ./actions/decrypt_kms
        with:
          key_ring: cfr
          keys: |
            rails_master_key: ./config/master.key.enc
            cfr_runner_key: ./config/cfr_runner.key.enc
            playstore_verifier_key: ./config/playstore_verifier.key.enc