on:
  workflow_dispatch:
    inputs:
      gcp_secret:
        description: 'GCP Secret'
        required: true

jobs:
  place_holder:
    name: None
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: cicd
          repository: Auddia/cicd
          ref: ${{ github.ref }}