name: '[Action Test] decrypt_kms_secret'

on:
  workflow_dispatch:
    inputs:
      gcp_secret:
        description: 'GCP Secret'
        required: true

jobs:
  decrypt_key:
    name: Decrypt Key
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: GCloud SDK Setup
        uses: ./actions/setup_gcloud
        with:
          gcp_credentials: ${{ github.event.inputs.gcp_secret }}

      - name: Get Single KMS File
        uses: ./actions/decrypt_kms_secrets
        with:
          key_ring: test
          input_dir: ./resources
          output_dir: ./decyphered_data
          decrypt_info: |
            test_key.key.enc : test_key : test_key.key

      - name: Validate Keys Were Created
        shell: bash
        run: |
          source ./scripts/test_functions.sh
          output=$(cat ./decyphered_data/test_key.key)
          expected="Hello World
          "
          fail_if_strings_unequal "$output" "$expected"