name: '[Action Test] build_and_publish_image'

on:
  workflow_dispatch:
    inputs:
      gcp_secret:
        description: 'GCP Secret'
        required: true

jobs:
  place_holder:
    name: None
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Build and Publish Image
        uses: ./actions/build_and_publish_image
        with:
          tag: "auddia_test_image"
          dockerfile: ./resources/test_docker_env/Dockerfile
          build_config: |
            TEST_ONE: ONE
            TEST_TWO: TWO

      - name: Pull Image
        shell: bash
        run: |
          docker pull auddia_test_image
          docker run auddia_test_image
